title: Deadlines with countdown!
description: Countdowns to some conference deadlines I'm interested, places where we submitted, conferences where existing works are.
author: Pascal Cotret

domain: ""
baseurl: "/deadlines-confs"

twitter_username: Pa0x73cal
github_username: pcotret
github_repo: deadlines-confs

markdown: kramdown

